[package]
name = "user"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
allocator = { path = "../allocator" }
spin = { path = "../spin" }
bitflags = "1.3.2"
fosix = { path = "../fosix" }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

[profile.release]
# opt-level = 0
debug = true